### ISSUE TITLE
Cannot find symbol androidx.camera.core.ImageProxy

### ISSUE THREAD

**Issue by caolong0204** [mateusz1913/vision-camera-plugin-builder#22]
### Environment

React-native:0.69.5
gradle: 7.3.3
OS:Android
after try to do step by step follow guide to create a plugin processor for android, i'm getting error below:
```
error: cannot find symbol
import androidx.camera.core.ImageProxy;
                           ^
  symbol:   class ImageProxy
  location: package androidx.camera.core
```

In My Android studio, import command is ok, but when build i'm getting this error.

Can anyone help me ?

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [X] android
- [ ] ios

### Current behavior

Cannot build success

### Expected behavior

Build Success

### Reproduction repository link

https://github.com/caolong0204/DemoScanBarCode go to branch **custom-plugin**

**Comment by caolong0204** [comment]
i found how to resolve my issue

**Comment by mateusz1913** [comment]
Hi @caolong0204, it seems to be problem with your setup, rather than plugin builder usage. Plugin builder was never meant to handle androidx camera dependencies - those should be handled by vision camera library itself. In fact, it's already handled [here](https://github.com/mrousavy/react-native-vision-camera/blob/b7bb8e45daf4edaf52243432315943261705b148/android/build.gradle#L290#L298), so if you had an error with lack of `androidx.camera.core.ImageProxy`, it's either setup problem or some version mismatch. Neither of those are related to plugin builder
